name: Release

on:
  push:
    tags:
      - 'v*'

# permissions
permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare release folder
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path release-folder
          Copy-Item -Path *.bat, README.md -Destination release-folder

      - name: Cleanup Files
        shell: powershell
        run: |
          Get-ChildItem -Path release-folder -Recurse -File | Unblock-File

      - name: Create ZIP archive
        shell: powershell
        run: |
          Compress-Archive -Path release-folder\* -DestinationPath devkit-tools.zip -CompressionLevel Optimal -Force

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: devkit-tools.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
